<?php

namespace Webkult\Api\Shirtigo\Requests\ImageApi;

use DateTime;
use Saloon\Enums\Method;
use Saloon\Http\Request;

/**
 * Get Rendering Tasks
 *
 * Retrieves a paginated list of mockup-factory rendering tasks for the authenticated user. This
 * endpoint can be used to
 * fetch all the rendering tasks generated by the user, allowing them to track
 * progress or results.
 * You can register a webhook for the event GeneratedMedia.rendered
 */
class GetRenderingTasks extends Request
{
	protected Method $method = Method::GET;


	public function resolveEndpoint(): string
	{
		return "/mockup-factory/rendering-tasks";
	}
}
